var weapons =
["una mina",
"un arco",
"melee",
"una paintball",
"un balón de baloncesto",
"un octobrush",
"un fidget spinner",
"un rifle de asalto",
"un frisbee",
"un tanque"];

var melee =
["una espada",
"un cuchillo",
"un palo de golf",
"un bate de baseball",
"un palo",
"una patata",
"un zapato",
"un ornitorrinco muerto",
"un 65",
"una espada de diamante",
"una doble espada",
"una calculadora TI-Nspire",
"una silla pregable",
"un mando de steam",
"una pera",
"un hacha de guerra",
"una gran espada",
"un mandoble victoriano",
"una espada corta",
"una maza",
"una botella de vodka"];

var itemsToFind =
["un árbol de fruta",
"un árbol de fruta venenosa",
"agua limpia",
"carbón limpio",
"col limpia",
"una maquina expendedora",
"un wild Ohio Fried Chicken",
"unas gafas que curan el daltonismo",
"una botella de lejía gomosa",
"un paintball",
"unas tiritas usadas",
"un paquete de condones",
"una carpa",
"un libro de biología",
"un cubo del KFC",
"un bote de bronceador de Donald Trump",
"un disco de la película de Emoji",
"una antología de poemas que cambian vidas",
"acero templado y revenido",
"una entrada VIP al concierto de Trebla",
"un unicornio",
"la luz espiritual en un folleto de Villareal",
"Lapras",
"un hacha de diamande",
"Stalin mustache",
"un zumo que daña los huesos",
"one spaghetti",
"un cupón del 50% de rebajas en Nintendo",
"un objeto indescriptible",
"algodón cubierto de chocolate con almendras",
"un desodorante de Ice Spice",
"un rayo congelante"];

var itemsThatGivePoints = [
"un árbol de frutas",
"agua limpia",
"unas gafas que curan el daltonismo",
"una antología de poemas que cambian vidas",
"un desodorante de Ice Spice",
"un cupón del 50% de rebajas en Nintendo",];

var causeAndEffect =
["un árbol de frutas",
"come frutas y gana un punto de fuerza",
"un árbol de fruta venenosas",
"se come una fruta venenosa",
"agua limpia",
"bebe agua limpia y gana un punto en constitución",
"carbón limpio",
"usa el carbón limpio para cocinar comidas",
"col limpia",
"usa la col limpio como alimento",
"una maquina expendedora",
"gana un bote de Monster mango loco",
"un wild Ohio Fried Chicken",
"random chicken",
"gafas que curan el daltonismo",
"ya no es daltónico",
"una botella de lejía gomosa",
"se bebe la botella de lejía gomosa",
"unas tiritas usadas",
"random bandaid",
"un paquete de condones",
"safe dating",
"una carpa",
"contruye una carpa",
"un libro de biología",
"lee un libro de biología y se queda dormido",
"un cubo del KFC",
"come KFC",
"un bote de bronceador de Donald Trump",
"se vuelves naranja como Donald Trump y mueres por intoxicación",
"disco de la película de Emoji",
"muere de cancer después de ver la película de Emoji",
"antología de poemas que cambian vidas",
"tu vida cambia gracias a los poemas",
"acero templado y revenido",
"contruye una armadura geométricamente estable",
"entrada VIP al concierto de Trebla",
"eres asaltado por un cepillo de dientes en el concierto de Trebla",
"unicornio",
"acaricia al peludo unicornio rosa",
"la luz espiritual en un folleto de Villareal",
"va a la luz y descubre que no hay nada en la ciudad",
"Lapras",
"ahora tendrá un increible amigo",
"hacha de diamante",
"minas diamante",
"zumo que daña los huesos",
"sufres un fuerte daño en tus huesos",
"mostacho de Stalin",
"gulag",
"one spaghetti",
"come un solitario y desdichado sphagetti",
"un cupón del 50% de rebajas en Nintendo",
"compra el Mario Kart World a 45€",
"un objeto indescribible",
"chicos ayuda soy lons, nathan me tiene secuestrado y me fuerza a no deciros que es este objeto",
"algodón cubierto de chocolate con almendras",
"tiene indigestión por comer demasiado algodón egipcio cubierto de chocolate con almendras",
"un desodorante de Ice Spice",
"reconoce que huele bien, pero es el desodorante de Ice Spice, no tu colonia habitual",
"un rayo congelante",
"se queda helado",
"email",
"muere de vergüenza al ser expulsado de su equipo de finanzas"];

var killCauseAndEffect =
["una mina",
"random mine",
"un arco",
"dispara a",
"melee",
"asesina a",
"una paintball",
"recubre de pintura a",
"un balón de baloncesto",
"le hace un mate a",
"un octobrush",
"splatoonado",
"un fidget spinner",
"gira el fidget spinner mortalmente a",
"un rifle de asalto",
"dispara a",
"un frisbee",
"decapita a",
"un tanque",
"asesina a"];

var shelter =
["una cueva",
"un árbol",
"una caja de cartulina",
"casa en el barrio de las 3000 viviendas de Sevilla",
"un cadáver de un caballo",
"un iglu",
"un jardín de olivos",
"un sofá",
"un saco para dormir",
"una cama de tamaño para una pareja con colchón de espuma viscoelástica y con reposacabezas amueblado",
"un burdel"];

var cornucopia =
["run",
"supply",
"weapon",
"battle"
];

var sponsor =
["una caja vacía",
"una paintball",
"unas tiritas usadas",
"agua limpia",
"un paquete de condones",
"una carpa",
"un libro de biología",
"un cubo del KFC",
"un bote de bronceador de Donald Trump",
"un disco de la película de Emoji",
"una antología de poemas que cambian vidas",
"acero templado y revenido",
"unos tickets VIP para el concierto de Trebla",
"Lapras",
"un hacha de diamante",
"Stalin moustache",
"zumo que hace daño a los huesos",
"one spaghetti",
"un cupón del 50% de descuento en Nintendo",
"un objeto indescribible",
"algodón cubierto de chocolate con almendras",
"un desodorante de Ice Spice",
"un rayo congelante"];

var misc =
["camina por ahí",
"agarra flores",
"saluda como Hitler",
"saluda como Hortler",
"habla con",
"se desahoga con",
"sube de nivel",
"nos canta una canción",
"es el sheriff",
"hace algunas bromas (SALIERON MAL Y SE VOLVIERON SEXUALES)",
"se da cuenta que México no tiene un filtro amarillo",
"pierde el juego",
"llora",
"tiene pesadillas",
"apuñala espárragos",
"se queda sin munición",
"es acusado de machismo",
"es raptado por Disney",
"es doxxeado por Chris Chan",
"se esconde en un río",
"se esconde de",
"come",
"ata una cinta métrica a una tostadora",
"gana un canal propio en Disney Channel",
"canta ópera",
"culpa a Daniel de todo",
"se convierte en un escritor literario",
"se queja de la nota del éxamen de parabolas",
"capturas 22",
"capturas en el centeno",
"eleva el requisito de la misión a 65",
"intenta publicar un Vine",
"logs",
"cambia de género",
"grita \"NikhilYA!\"",
"encuentra a Pepe",
"encuentra a Chuck Norris",
"pone químicos al agua para volver a las ranas gays",
"pelea contra el Ender dragon",
"ve Hora de Aventuras por 3 horas",
"se une a la Sociedad de la prevención de suicidio en los adolescentes",
"encuentra a Chuck Norris",
"rollos de barril",
"encuentra a Dory",
"encuentra a Nemo",
"se siente muy Bandu"];

var injury =
["se resfría",
"tiene gripe",
"tiene faringitis estreptocócica",
"Pierde 0,13 puntos de GPA y resulta gravemente herido.",
"es picado por abejas",
"batallas y heridas",
"envia muchísimos correos",
"se queda sordo por Jake Paul",
"tiene síndrome del túnel carpiano por jugar al osu",
"tiene osteoporosis",
"tiene depresión",
"intenta romper la cuarta pared",
"hace bromas telefónicas",
"ve las cosas varias veces",
"ve las cosas una sola vez",
"lee un fatidico mensaje escrito en Comic Sans",
"se resbala y se desliza por la cáscara de plátano",
"tiene linfoma",
"tiene una infección en la vejiga",
"es herido cuando una tribu nativa de la zona le quita las uñas",
"tiene un devastador hipo",
"tiene fiebre amarilla",
"esta obligado a convivir con abejas",
"es asado por un pollo gigante. '¡Espabila!' dice el pollo sanguinareamente",
"por su mala suerte tropieza a pesar de tener una probabilidad de 1/100",
"tiene una úlcera",
"desarrolla cancér cerebral en etapa 4",
"tiene necrosis",
"es obligado a obedecer ante un mentor"];

var injEffect =
["dispara a",
"lesion",
"pelea",
"paintball",
"es disparado por un tiro de paintball de",
"basketball",
"es juzgado por",
"octobrush",
"heridas",
"fidget spinner",
"gira el fidget spinner de forma no mortal a",
"rifle de asalto",
"dispara y le roza"];

var variousDeaths =
["es estrangulado",
"rompe",
"muere de Ebola",
"es aplastado por una armadura inestable",
"es asesinado por la Agencia de Defensa Ámericana, llamados por",
"es quedamo hasta morir por",
"se cuelga",
"decide tomarse una siesta permanente",
"se cae de un precipicio por jugar a Pokémon GO",
"grita \"Dojyaaa ~ n\" hacia",
"es atacado con bombas órbitales por",
"se olvida de como respirar",
"usa memes antiguos para matar a",
"acabado por la marina de guerra",
"unsafe dating",
"es golpeado por un huracán",
"caé a un portal que lo transportar a una dimensión LLENA de batidora",
"pierde la circulación de la sangre por llevar esos espéctaculares pantalones cortos super ajustados",
"pierde circulación a sentir demasiado apretado sus buenos pantalones cortos",
"caé al vacío",
"es asesinado por un pigglin zombie",
"se marchita",
"stream",
"suspende un examén en Oxford y muere",
"muere tras una cirugía fallida para borrar una marca de nacimiento con forma de Homero",
"maldice un grupo cristiano y lo golpean hasta la muerte",
"se quema espontáneamente",
"se desconecto del server",
"se cuelga como si fuese un perchero",
"cae en un pozo",
"muere en la Matrix",
"sucumbe a la letal presión de",
"acepta y termina el juego de la ballena azul"];

var doubleDeath =
["es estrangulado por",
"usa memes antiguos para matar a",
"sucumbe a la letal presión de"];

var options =
["weapons",
"items",
"use",
"shelter",
"use",
"misc",
"injury",
"use",
"death",
"heal",
"items",
"use",
"injury",
"use"];

var vowels = ["a","e","i","o","u"];
